name: "Chromatic Deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
            if [ ${{ env.yarn-cache-hit }} != 'true' ]; then
                echo "Installing all dependencies..."
                yarn install --immutable --immutable-cache --check-cache
            else
                echo "Restoring .yarn/cache from cache..."
                yarn install --immutable
            fi

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build-storybook

      - name: Checking Chromatic at PR
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: "✨스토리북 확인하기: ${{ steps.chromatic.outputs.storybookUrl }}"