name: Lint Check

on: pull_request

jobs:
  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ./yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Check for Cached Dependencies
        id: cache-check
        run: |
          if [ -d .yarn/cache ]; then
            echo "Cache found!"
            echo "cache-hit=true" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        if: steps.cache-check.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Lint
        run: yarn lint
